name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: addition
      id: addition
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 3
        setup-command: ''
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        KUBOID_RESULTS: "${{steps.kuboid.outputs.result}}"
      with:
        runners: addition
